language: node_js
node_js:
  - "8"
  - "node"
matrix:
  include:
  - node_js: node
    env: TEST_BROWSERS=true
before_install:
  - cd travis
  - wget --no-check-certificate https://www.antlr.org/download/antlr-4.7.1-complete.jar
  - export CLASSPATH=".:$TRAVIS_BUILD_DIR/travis/antlr-4.7.1-complete.jar:$CLASSPATH"
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/travis
  - cd ..
  - cd js && npm install && cd ..
  - pip install --user pipenv
  - pipenv install --dev
script:
  - make
  - npm test
  - npm run fmt
  - git diff --quiet
