language: node_js
node_js:
  - "6"
  - "8"
  - "node"
matrix:
  include:
  - node_js: node
    env: TEST_BROWSERS=true
before_install:
  - cd travis
  - wget --no-check-certificate https://www.antlr.org/download/antlr-4.7.1-complete.jar
  - export CLASSPATH=".:$TRAVIS_BUILD_DIR/travis/antlr-4.7.1-complete.jar:$CLASSPATH"
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/travis
  - cd ..
script:
  - make
  - cd js
  - yarn
  - yarn test
  - if [ "${TEST_BROWSERS}" = "true" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then yarn test:sauce; fi
